output "cluster_endpoint" {
  description = "Endpoint for GKE control plane."
  sensitive   = true
  value       = module.gke.endpoint
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  sensitive   = true
  value       = module.gke_auth.kubeconfig_raw
}

output "region" {
  description = "GCP region."
  value       = var.region
}

output "cluster_id" {
  value = var.cluster_id
}

output "cluster_name" {
  value = var.cluster_name
}

output "cluster_name_short" {
  value = local.cluster_name_short
}

output "dns_zone" {
  value = {
    zone_id : local.zone_name,
    name : local.domain,
    name_servers : module.dns.name_servers,
  }
}